### ISSUE TITLE
On 2.1.0-dev.9.4.flutter-f9ebf21297 version solving fails

### ISSUE THREAD

**Issue by dancingbannana** [YevhenKap/ai#1]
This is the compiler output:

The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because untitled1 depends on ai >=0.1.2 which requires SDK version >=2.1.0 <3.0.0, version solving failed.

pub get failed (1)

**Comment by Kapelianovych** [comment]
@dancingbannana hello. This is because of Flutter use old dev version of Dart `2.1.0-dev.9.4`, which is right before stable `2.1.0`. In next minor patch I downgrade Dart version.
